### PR TITLE
Ecommerce app with Stripe payment processor

### PR DESCRIPTION
**Pull request by pomegranited**
**Note** Actually merged to branch [`release-bit`](https://github.com/BehavioralInsightsTeam/ecommerce/tree/release-bit), not `master`.

This PR merges the latest edx/ecommerce:master with @jbzdak 's PR #601.

Note: Upstream has changed a bit since the PR was submitted, and so there were a few changes required (see @pomegranited commits at the bottom).

**JIRA tickets**: [OC-1434](https://tasks.opencraft.com/browse/OC-1434)

**Testing instructions**
1. Set up a dogwood devstack: 

``` bash
export OPENEDX_RELEASE="named-release/dogwood.rc"
curl -L https://raw.githubusercontent.com/edx/configuration/master/vagrant/release/devstack/Vagrantfile > Vagrantfile
vagrant plugin install vagrant-vbguest
vagrant up
```
1. Update software versions: 

``` bash
cd edx-platform
git remote add bit git@github.com:BehavioralInsightsTeam/edx-platform.git
git fetch bit
git checkout -b jill/upstream.release-2016-03-30 bit/jill/upstream.release-2016-03-30
cd ..

cd ecommerce
git remote add bit git@github.com:BehavioralInsightsTeam/ecommerce.git
git fetch bit
git checkout -b jill/jbzdak/stripe bit/jill/jbzdak/stripe
cd ..

cd theme
git clone git@github.com:BehavioralInsightsTeam/edx-theme.git bit
cd bit
git checkout -b bit origin/bit
cd ../..
```
1. Update config to match [vars.yml](https://github.com/BehavioralInsightsTeam/bit-configuration-secure/blob/cf809bf5f1e0b75d16e083de8843b9b9a36e3524/vars.yml):
   - `/edx/app/edxapp/lms.env.json`
   
   ``` diff
   --- lms.env.json.orig   2016-05-11 00:25:58.943750885 +0000
   +++ lms.env.json    2016-05-11 13:32:53.439812980 +0000
   @@ -95,7 +95,7 @@
    }, 
    "COMMENTS_SERVICE_KEY": "password", 
    "COMMENTS_SERVICE_URL": "http://localhost:18080", 
   -    "COMPREHENSIVE_THEME_DIR": "", 
   +    "COMPREHENSIVE_THEME_DIR": "/edx/app/edxapp/themes/bit", 
    "CONTACT_EMAIL": "info@example.com", 
    "CORS_ORIGIN_ALLOW_ALL": false, 
    "CORS_ORIGIN_WHITELIST": [], 
   @@ -144,7 +144,23 @@
        "ENABLE_VIDEO_BEACON": false, 
        "ENABLE_VIDEO_UPLOAD_PIPELINE": false, 
        "PREVIEW_LMS_BASE": "", 
   -        "USE_CUSTOM_THEME": false
   +
   +        "USE_CUSTOM_THEME": false,
   +        "USE_MICROSITES": false,
   +        "THEME_NAME": "bit",
   +        "AUTH_USE_OPENID": false, 
   +        "AUTH_USE_OPENID_PROVIDER": false, 
   +        "CERTIFICATES_ENABLED": false, 
   +        "ENABLE_INSTRUCTOR_ANALYTICS": true, 
   +        "ENABLE_INSTRUCTOR_EMAIL": true, 
   +        "REQUIRE_COURSE_EMAIL_AUTH": false,
   +        "ENABLE_PEARSON_HACK_TEST": false,
   +        "SUBDOMAIN_BRANDING": false,
   +        "SUBDOMAIN_COURSE_LISTINGS": false,
   +        "ENABLE_DJANGO_ADMIN_SITE": true,
   +        "ALLOW_ALL_ADVANCED_COMPONENTS": true,
   +        "ENABLE_COMBINED_LOGIN_REGISTRATION": true,
   +        "ENABLE_S3_GRADE_DOWNLOADS": true
    }, 
    "FEEDBACK_SUBMISSION_EMAIL": "", 
    "FILE_UPLOAD_STORAGE_BUCKET_NAME": "edxuploads", 
   @@ -217,7 +233,8 @@
        "country": "hidden", 
        "gender": "optional", 
        "goals": "optional", 
   -        "honor_code": "required", 
   +        "honor_code": "hidden", 
   +        "terms_of_service": "hidden", 
        "level_of_education": "optional", 
        "mailing_address": "optional", 
        "year_of_birth": "optional"
   @@ -246,7 +263,7 @@
    "TENDER_DOMAIN": null, 
    "TENDER_SUBDOMAIN": null, 
    "THEME_NAME": "", 
   -    "TIME_ZONE": "America/New_York", 
   +    "TIME_ZONE": "UTC",
    "UNIVERSITY_EMAIL": "university@example.com", 
    "VIDEO_CDN_URL": {
        "EXAMPLE_COUNTRY_CODE": "http://example.com/edx/video?s3_url="
   ```
   - `/edx/app/edxapp/cms.env.json`
   
   ``` diff
   --- cms.env.json.orig   2016-05-11 00:25:52.567842781 +0000
   +++ cms.env.json    2016-05-11 13:33:06.579838060 +0000
   @@ -120,7 +120,23 @@
        "ENABLE_VIDEO_BEACON": false, 
        "ENABLE_VIDEO_UPLOAD_PIPELINE": false, 
        "PREVIEW_LMS_BASE": "", 
   -        "USE_CUSTOM_THEME": false
   +
   +        "USE_CUSTOM_THEME": false,
   +        "USE_MICROSITES": false,
   +        "THEME_NAME": "bit",
   +        "AUTH_USE_OPENID": false, 
   +        "AUTH_USE_OPENID_PROVIDER": false, 
   +        "CERTIFICATES_ENABLED": false, 
   +        "ENABLE_INSTRUCTOR_ANALYTICS": true, 
   +        "ENABLE_INSTRUCTOR_EMAIL": true, 
   +        "REQUIRE_COURSE_EMAIL_AUTH": false,
   +        "ENABLE_PEARSON_HACK_TEST": false,
   +        "SUBDOMAIN_BRANDING": false,
   +        "SUBDOMAIN_COURSE_LISTINGS": false,
   +        "ENABLE_DJANGO_ADMIN_SITE": true,
   +        "ALLOW_ALL_ADVANCED_COMPONENTS": true,
   +        "ENABLE_COMBINED_LOGIN_REGISTRATION": true,
   +        "ENABLE_S3_GRADE_DOWNLOADS": true
    }, 
    "FEEDBACK_SUBMISSION_EMAIL": "", 
    "FILE_UPLOAD_STORAGE_BUCKET_NAME": "edxuploads", 
   @@ -167,7 +183,8 @@
        "country": "hidden", 
        "gender": "optional", 
        "goals": "optional", 
   -        "honor_code": "required", 
   +        "honor_code": "hidden", 
   +        "terms_of_service": "hidden", 
        "level_of_education": "optional", 
        "mailing_address": "optional", 
        "year_of_birth": "optional"
   @@ -196,7 +213,7 @@
    "TENDER_DOMAIN": null, 
    "TENDER_SUBDOMAIN": null, 
    "THEME_NAME": "", 
   -    "TIME_ZONE": "America/New_York", 
   +    "TIME_ZONE": "UTC",
    "UNIVERSITY_EMAIL": "university@example.com", 
    "VIDEO_UPLOAD_PIPELINE": {
        "BUCKET": "", 
   ```
   - `/edx/app/ecommerce/ecommerce/ecommerce/settings/private.py`
   
   **Note:** The stripe configuration details in the PR vars.yml are BIT's production values.  Please use the [test credentials from your own stripe account](https://dashboard.stripe.com/account/apikeys) instead.
   
   ``` python
   from ._oscar import PAYMENT_PROCESSOR_RECEIPT_PATH, PAYMENT_PROCESSOR_CANCEL_PATH, PAYMENT_PROCESSOR_ERROR_PATH
   
   PAYMENT_PROCESSOR_CONFIG = {
   'edx': {
       'stripe': {
           'publishable_key': 'x',
           'secret_key': 'x',
           'image_url': '/static/images/default-theme/logo.png',
           'receipt_path': PAYMENT_PROCESSOR_RECEIPT_PATH,
           'cancel_path': PAYMENT_PROCESSOR_CANCEL_PATH,
           'error_path': PAYMENT_PROCESSOR_ERROR_PATH,
       },
   }
   }
   ```
2. Update run migrations and update requirements

``` bash
sudo su edxapp
./manage.py lms migrate --settings=devstack
```

``` bash
sudo su ecommerce
make requirements
./manage.py switch payment_processor_active_stripe on --create
python manage.py create_or_update_site --site-id=1 \
                --site-domain=localhost:8002 \
                --partner-code=edX \
                --partner-name='Open edX' \
                --lms-url-root=http://localhost:8000 \
                --theme-scss-path=sass/themes/edx.scss \
                --payment-processors=Stripe \
                --client-id=ecommerce-key \
                --client-secret=ecommerce-secret
```
1. Run services

``` bash
sudo su ecommerce
make serve
```

``` bash
sudo su edxapp
paver devstack lms
```

``` bash
sudo su edxapp
paver devstack cms
```
1. Set up ecommerce:
   - create a superuser so you can access the Admin area
   - http://localhost:8000/admin/commerce/commerceconfiguration/ -- Add new Commerce Configuration, with Active True, checkout on, ecommerce True, checkout URL /basket/single-item/ (the default)
   - http://localhost:8001 -- Add a new test course
   - http://localhost:8002/courses -- Enter the details of your test course.  Course Type: Professional Education, min cost $5
2. [Ecommerce test instructions are well-documented by Jacek](https://docs.google.com/document/d/1yDDuRaIzbn3nMKDFRKV-cBd7JSPgxVktw6iBWbg9md4/edit#heading=h.3nnyxcsymae1) from [PR 601](https://github.com/edx/ecommerce/pull/601).
3. Test registration form by registering a new student account.  Ensure you don't have to agree to the Honor Code or the Terms and Conditions.
4. Run unit tests

``` bash
sudo su ecommece
python manage.py compress --settings=ecommerce.settings.test
xvfb-run --auto-servernum make validate
```

**Author notes and concerns**:
1. Need to merge changes from OC-1350 when they are ready.
2. The Studio logo needs updating.

**Reviewers**
- [ ] @mtyaka

### CODE REVIEW

**Comment by jbzdak** [comment]
NIT: I needed to run `make static` in ecommerce. 
NIT: `git checkout -b jill/upstream-release-2016-03-30 bit/jill/upstream-release-2016-03-30` -> `git checkout -b jill/upstream-release-2016-03-30` 

I would like to thank you for these setup instructions, they were a great help.

**Comment by pomegranited** [comment]
@jbzdak I'm glad the instructions were helpful 😄   And thanks for the nits; I've updated the description.

**Comment by mtyaka** [comment]
nit: `jill/upstream-release-2016-03-30` branch is actually named `jill/upstream.release-2016-03-30`

**Comment by mtyaka** [comment]
In

```
python manage.py create_or_update_site --site-id=1 \
                --site-domain=localhost:8002 \
                --partner-code=edX \
                --partner-name='Open edX' \
                --lms-url-root=http://localhost:8000 \
                --theme-scss-path=sass/themes/edx.scss \
                --payment-processors=Stripe \
                --client-id=ecommerce-key \
                --client-secret=ecommerce-secret
```

I had to change `--payment-processors=Stripe` to `--payment-processors=stripe` or the ecommerce service would fail to start.

**Comment by mtyaka** [comment]
👍

**Pull request merged**
